### ISSUE TITLE
API ?

### ISSUE THREAD

**Issue by marsalans** [dleonard0/pktstat#5]
Hi @dleonard0 
I recently see your software which is great indeed. We previously use HSF which shows stats of IP with GET request but we move from Windows to Linux but we lack support to monitor that in as single window.

Now i have seen your software and this is what i wanted, but as we move to linux we also add more servers now we need an API to connect all these servers.

I just need only API to see ip of cleints and get request, i will create UI

**Comment by dleonard0** [comment]
This seems to be a request for an API to have pktstat monitor GET requests made on HTTP servers?
The pcap filter expression and other command line options are pktstat's only API.
For example, `pktstat 'tcp port 80'`. See [pcap-filter(7)](https://www.tcpdump.org/manpages/pcap-filter.7.html).
If this is insufficient, pktstat may not be the right tool for you; See for example [tcpgrep](https://github.com/weary/tcpgrep).
